module.exports = [
    {
        'id': 1,
        'street': '123 Main St',
        'postalCode': '12345',
        'state': 'California',
        'city': 'Los Angeles',
        'userId': 1,
    },
    {
        'id': 2,
        'street': '456 Oak St',
        'postalCode': '67890',
        'state': 'New York',
        'city': 'New York City',
        'userId': 1,
    },
    {
        'id': 3,
        'street': '789 Pine St',
        'postalCode': '54321',
        'state': 'Texas',
        'city': 'Houston',
        'userId': 1,
    },
    {
        'id': 4,
        'street': '101 Maple Ave',
        'postalCode': '98765',
        'state': 'Florida',
        'city': 'Miami',
        'userId': 2,
    },
    {
        'id': 5,
        'street': '202 Cedar Blvd',
        'postalCode': '23456',
        'state': 'Illinois',
        'city': 'Chicago',
        'userId': 2,
    },
    {
        'id': 6,
        'street': '303 Pine Ln',
        'postalCode': '87654',
        'state': 'Arizona',
        'city': 'Phoenix',
        'userId': 3,
    },
];
