module.exports = [
    {
        'id': 1,
        'title': 'Classic Watch',
        'description': 'A timeless piece for every occasion.',
        'price': 99.99,
        'availableInStock': 50,
        'totalRating': 4.7,
        'ratingCount': 25,
        'imageUrl': 'https://example.com/classic-watch.jpg',
        'categoryId': 2,
        'brandId': 1,
        'discountId': 3
    },
    {
        'id': 2,
        'title': 'Leather Handbag',
        'description': 'Elegance in every detail, crafted with genuine leather.',
        'price': 129.99,
        'availableInStock': 30,
        'totalRating': 4.5,
        'ratingCount': 18,
        'imageUrl': 'https://example.com/leather-handbag.jpg',
        'categoryId': 1,
        'brandId': 2,
        'discountId': 1
    },
    {
        'id': 3,
        'title': 'Aviator Sunglasses',
        'description': 'Protect your eyes with style.',
        'price': 59.99,
        'availableInStock': 40,
        'totalRating': 4.8,
        'ratingCount': 22,
        'imageUrl': 'https://example.com/aviator-sunglasses.jpg',
        'categoryId': 3,
        'brandId': 3,
        'discountId': 2
    },
    {
        'id': 4,
        'title': 'Fedora Hat',
        'description': 'A classic accessory for a touch of sophistication.',
        'price': 34.99,
        'availableInStock': 25,
        'totalRating': 4.2,
        'ratingCount': 15,
        'imageUrl': 'https://example.com/fedora-hat.jpg',
        'categoryId': 4,
        'brandId': 1,
        'discountId': 2
    },
    {
        'id': 5,
        'title': 'Diamond Necklace',
        'description': 'Shine bright with this exquisite diamond necklace.',
        'price': 299.99,
        'availableInStock': 15,
        'totalRating': 4.9,
        'ratingCount': 30,
        'imageUrl': 'https://example.com/diamond-necklace.jpg',
        'categoryId': 5,
        'brandId': 2,
        'discountId': 1
    },
    {
        'id': 6,
        'title': 'Stylish Backpack',
        'description': 'Versatile and trendy, perfect for daily adventures.',
        'price': 79.99,
        'availableInStock': 35,
        'totalRating': 4.6,
        'ratingCount': 20,
        'imageUrl': 'https://example.com/stylish-backpack.jpg',
        'categoryId': 1,
        'brandId': 3,
        'discountId': 2
    },
    {
        'id': 7,
        'title': 'Silver Bracelet',
        'description': 'Add a touch of elegance to your wrist.',
        'price': 49.99,
        'availableInStock': 28,
        'totalRating': 4.4,
        'ratingCount': 17,
        'imageUrl': 'https://example.com/silver-bracelet.jpg',
        'categoryId': 5,
        'brandId': 1,
        'discountId': 3
    },
    {
        'id': 8,
        'title': 'Wide-Brim Hat',
        'description': 'Stay stylish and sun-protected.',
        'price': 39.99,
        'availableInStock': 22,
        'totalRating': 4.0,
        'ratingCount': 12,
        'imageUrl': 'https://example.com/wide-brim-hat.jpg',
        'categoryId': 4,
        'brandId': 2,
        'discountId': 2
    },
    {
        'id': 9,
        'title': 'Gold Earrings',
        'description': 'Accentuate your look with these dazzling gold earrings.',
        'price': 89.99,
        'availableInStock': 18,
        'totalRating': 4.8,
        'ratingCount': 26,
        'imageUrl': 'https://example.com/gold-earrings.jpg',
        'categoryId': 5,
        'brandId': 3,
        'discountId': 1
    },
    {
        'id': 10,
        'title': 'Modern Wristwatch',
        'description': 'Sleek design for the contemporary lifestyle.',
        'price': 119.99,
        'availableInStock': 32,
        'totalRating': 4.3,
        'ratingCount': 19,
        'imageUrl': 'https://example.com/modern-wristwatch.jpg',
        'categoryId': 2,
        'brandId': 1,
        'discountId': 1
    },
    {
        'id': 11,
        'title': 'Canvas Tote Bag',
        'description': 'A stylish and spacious tote for everyday use.',
        'price': 49.99,
        'availableInStock': 40,
        'totalRating': 4.5,
        'ratingCount': 23,
        'imageUrl': 'https://example.com/canvas-tote-bag.jpg',
        'categoryId': 1,
        'brandId': 2,
        'discountId': 2
    },
    {
        'id': 12,
        'title': 'Sporty Backpack',
        'description': 'Perfect for the active lifestyle, designed for comfort.',
        'price': 64.99,
        'availableInStock': 35,
        'totalRating': 4.2,
        'ratingCount': 15,
        'imageUrl': 'https://example.com/sporty-backpack.jpg',
        'categoryId': 1,
        'brandId': 3,
        'discountId': 3
    },
    {
        'id': 13,
        'title': 'Pearl Necklace',
        'description': 'Timeless elegance with a string of pearls.',
        'price': 179.99,
        'availableInStock': 20,
        'totalRating': 4.9,
        'ratingCount': 29,
        'imageUrl': 'https://example.com/pearl-necklace.jpg',
        'categoryId': 5,
        'brandId': 1,
        'discountId': 1
    },
    {
        'id': 14,
        'title': 'Leather Wallet',
        'description': 'Classic design with multiple compartments for your essentials.',
        'price': 29.99,
        'availableInStock': 50,
        'totalRating': 4.3,
        'ratingCount': 18,
        'imageUrl': 'https://example.com/leather-wallet.jpg',
        'categoryId': 1,
        'brandId': 2,
        'discountId': 2
    },
    {
        'id': 15,
        'title': 'Retro Sunglasses',
        'description': 'Channel your inner vintage with these stylish shades.',
        'price': 54.99,
        'availableInStock': 30,
        'totalRating': 4.7,
        'ratingCount': 22,
        'imageUrl': 'https://example.com/retro-sunglasses.jpg',
        'categoryId': 3,
        'brandId': 3,
        'discountId': 3
    },
    {
        'id': 16,
        'title': 'Silver Cuff Bracelet',
        'description': 'A statement piece to elevate your wristwear.',
        'price': 69.99,
        'availableInStock': 25,
        'totalRating': 4.6,
        'ratingCount': 21,
        'imageUrl': 'https://example.com/silver-cuff-bracelet.jpg',
        'categoryId': 5,
        'brandId': 1,
        'discountId': 2
    },
    {
        'id': 17,
        'title': 'Panama Hat',
        'description': 'Stay cool and stylish under the sun.',
        'price': 44.99,
        'availableInStock': 28,
        'totalRating': 4.1,
        'ratingCount': 16,
        'imageUrl': 'https://example.com/panama-hat.jpg',
        'categoryId': 4,
        'brandId': 2,
        'discountId': 1
    },
    {
        'id': 18,
        'title': 'Rose Gold Earrings',
        'description': 'Add a touch of warmth with these elegant rose gold earrings.',
        'price': 99.99,
        'availableInStock': 18,
        'totalRating': 4.8,
        'ratingCount': 27,
        'imageUrl': 'https://example.com/rose-gold-earrings.jpg',
        'categoryId': 5,
        'brandId': 3,
        'discountId': 3
    },
    {
        'id': 19,
        'title': 'Minimalist Wristwatch',
        'description': 'Simplicity meets sophistication in this modern timepiece.',
        'price': 89.99,
        'availableInStock': 32,
        'totalRating': 4.4,
        'ratingCount': 19,
        'imageUrl': 'https://example.com/minimalist-wristwatch.jpg',
        'categoryId': 2,
        'brandId': 1,
        'discountId': 2
    },
    {
        'id': 20,
        'title': 'Crystal Pendant Necklace',
        'description': 'Capture the light with this dazzling crystal pendant.',
        'price': 129.99,
        'availableInStock': 15,
        'totalRating': 4.9,
        'ratingCount': 31,
        'imageUrl': 'https://example.com/crystal-pendant-necklace.jpg',
        'categoryId': 5,
        'brandId': 2,
        'discountId': 1
    },

    {
        'id': 21,
        'title': 'Leather Crossbody Bag',
        'description': 'Compact and versatile, perfect for on-the-go.',
        'price': 74.99,
        'availableInStock': 22,
        'totalRating': 4.5,
        'ratingCount': 25,
        'imageUrl': 'https://example.com/leather-crossbody-bag.jpg',
        'categoryId': 1,
        'brandId': 3,
        'discountId': 3
    },
    {
        'id': 22,
        'title': 'Diamond Stud Earrings',
        'description': 'Timeless elegance with a touch of sparkle.',
        'price': 149.99,
        'availableInStock': 17,
        'totalRating': 4.8,
        'ratingCount': 29,
        'imageUrl': 'https://example.com/diamond-stud-earrings.jpg',
        'categoryId': 5,
        'brandId': 1,
        'discountId': 1
    },
    {
        'id': 23,
        'title': 'Laptop Backpack',
        'description': 'Stay organized and stylish with this tech-friendly backpack.',
        'price': 89.99,
        'availableInStock': 20,
        'totalRating': 4.6,
        'ratingCount': 22,
        'imageUrl': 'https://example.com/laptop-backpack.jpg',
        'categoryId': 1,
        'brandId': 2,
        'discountId': 3
    },
    {
        'id': 24,
        'title': 'Gold Link Bracelet',
        'description': 'Make a statement with this bold and trendy gold link bracelet.',
        'price': 79.99,
        'availableInStock': 19,
        'totalRating': 4.3,
        'ratingCount': 18,
        'imageUrl': 'https://example.com/gold-link-bracelet.jpg',
        'categoryId': 5,
        'brandId': 3,
        'discountId': 2
    },
    {
        'id': 25,
        'title': 'Classic Aviator Sunglasses',
        'description': 'Achieve a timeless look with these iconic aviator shades.',
        'price': 59.99,
        'availableInStock': 25,
        'totalRating': 4.7,
        'ratingCount': 21,
        'imageUrl': 'https://example.com/classic-aviator-sunglasses.jpg',
        'categoryId': 3,
        'brandId': 1,
        'discountId': 3
    }
];
